const canvas = document.getElementById('arena');
const ctx = canvas.getContext('2d');
const keys = new Set();
const TAU = Math.PI * 2;
const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
const roster = {
  samurai: { name:'SAMURAI', color:'#8bd8c1', accent:'#c8f3e5', hp:100, guard:50, speed:260, damage:9, skill:'PARRY', ult:'IAIDO FINAL', mana:0 },
  necromancer: { name:'NECROMANCER', color:'#b08cff', accent:'#e0d3ff', hp:90, guard:50, speed:210, damage:60, skill:'CORPSE CALL', ult:'GRAVE DOMAIN', mana:100 },
  soldier: { name:'SOLDIER', color:'#d8b765', accent:'#f6e2a4', hp:100, guard:50, speed:235, damage:8, skill:'WEAPON SWAP', ult:'FULL AUTO', mana:0 },
  swat: { name:'S.W.A.T.', color:'#ff725f', accent:'#ffc2b8', hp:115, guard:70, speed:180, damage:6, skill:'FLASHBANG', ult:'BACKUP UNIT', mana:0 }
};
const p1Select = document.getElementById('p1Select'); const p2Select = document.getElementById('p2Select');
Object.entries(roster).forEach(([id, data]) => { p1Select.add(new Option(data.name, id)); p2Select.add(new Option(data.name, id)); }); p1Select.value='samurai'; p2Select.value='necromancer';
let game = null;
function createFighter(id, side) { const base=roster[id]; return {id,side,base,x:side===1?270:930,y:500,vx:0,hp:base.hp,guard:base.guard,stamina:100,mana:id==='necromancer'?0:base.mana,ult:0,facing:side===1?1:-1,state:'idle',stateTime:0,attackTime:0,attackKind:'',attackRange:125,cooldown:0,skillCooldown:0,combo:0,comboDamage:0,comboTimer:0,wins:0,flash:0,dodge:0,invuln:0,perfect:0,corpses:0,summons:0,bindTime:0,areaTime:0,areaTick:0,slowUntil:0}; }
function beginMatch(){game={round:1,timer:60,running:true,roundOver:false,announce:'ROUND 1',announceTime:1.8,fighters:[createFighter(p1Select.value,1),createFighter(p2Select.value,2)],objects:[{x:590,y:530,w:62,h:58,type:'crate'},{x:690,y:530,w:46,h:62,type:'chair'}],particles:[]};updateHud();document.getElementById('selectScreen').classList.add('hidden');document.getElementById('gameScreen').classList.remove('hidden');document.getElementById('matchStatus').textContent='LIVE MATCH';requestAnimationFrame(loop);}
document.getElementById('startButton').addEventListener('click',beginMatch);
const controls={1:{left:'a',right:'d',guard:'h',light:'f',heavy:'g',dodge:'j',skill:'k',bind:'i',ult:'l'},2:{left:'ArrowLeft',right:'ArrowRight',guard:'3',light:'1',heavy:'2',dodge:'4',skill:'5',bind:'7',ult:'6'}};
window.addEventListener('keydown',event=>{keys.add(event.key);if(event.key.toLowerCase()==='r'&&game)beginMatch();});window.addEventListener('keyup',event=>keys.delete(event.key));
function fighterInput(f){const c=controls[f.side];return{left:keys.has(c.left),right:keys.has(c.right),guard:keys.has(c.guard),light:keys.has(c.light),heavy:keys.has(c.heavy),dodge:keys.has(c.dodge),skill:keys.has(c.skill),bind:keys.has(c.bind),ult:keys.has(c.ult)};}
function announce(text,time=1.2){game.announce=text;game.announceTime=time;} function burst(x,y,color,count=12){for(let i=0;i<count;i++)game.particles.push({x,y,vx:(Math.random()-.5)*280,vy:(Math.random()-.8)*260,life:.5+Math.random()*.4,color,size:2+Math.random()*4});}
function updateFighter(f,e,dt){if(f.hp<=0)return;const i=fighterInput(f);f.cooldown=Math.max(0,f.cooldown-dt);f.skillCooldown=Math.max(0,f.skillCooldown-dt);f.stateTime=Math.max(0,f.stateTime-dt);f.attackTime=Math.max(0,f.attackTime-dt);f.comboTimer=Math.max(0,f.comboTimer-dt);f.invuln=Math.max(0,f.invuln-dt);f.flash=Math.max(0,f.flash-dt);f.bindTime=Math.max(0,f.bindTime-dt);f.slowUntil=Math.max(0,f.slowUntil-dt);if(f.areaTime>0){f.areaTime=Math.max(0,f.areaTime-dt);f.areaTick-=dt;if(f.id==='necromancer')f.mana=clamp(f.mana+dt*8,0,100);if(f.areaTick<=0&&Math.abs(f.x-e.x)<260){f.areaTick=1;e.hp=clamp(e.hp-30,0,e.base.hp);e.state='hit';e.stateTime=.2;f.ult=clamp(f.ult+4,0,100);if(e.hp<=0)finishRound(f);}}if(f.comboTimer===0){f.combo=0;f.comboDamage=0;}f.stamina=clamp(f.stamina+dt*22,0,100);f.facing=e.x>=f.x?1:-1;if(f.state==='stun'){if(f.stateTime<=0)f.state='idle';return;}if(f.state==='hit'){if(f.stateTime<=0)f.state='idle';return;}if(i.dodge&&f.stamina>=28&&f.cooldown===0){f.stamina-=28;f.invuln=.35;f.dodge=.28;f.vx=f.facing*-f.base.speed*1.5;f.cooldown=.5;burst(f.x,f.y,'#d7dfd3',5);return;}if(i.guard&&f.attackTime===0){if(f.state!=='guard')f.perfect=.1;f.state='guard';f.vx=0;return;}if(f.state==='guard')f.state='idle';if(f.attackTime===0){if(i.ult&&f.ult>=100)useUltimate(f,e);else if(f.id==='necromancer'&&i.bind&&f.skillCooldown===0)useBinding(f,e);else if(i.skill&&f.skillCooldown===0)useSkill(f,e);else if(f.cooldown===0&&i.heavy&&((f.id!=='necromancer'&&f.stamina>=18)||f.id==='necromancer'))startAttack(f,'heavy');else if(f.cooldown===0&&i.light)startAttack(f,'light');}const d=(i.right?1:0)-(i.left?1:0);if(f.attackTime===0&&f.state!=='guard'){f.vx=d*f.base.speed*(f.slowUntil>0?.3:1);f.x=clamp(f.x+f.vx*dt,70,1130);}if(f.attackTime>0){const active=f.attackTime<(f.id==='necromancer'&&f.attackKind==='heavy'?.7:.34)&&f.attackTime>.12;if(active&&!f._hitThisAttack&&Math.abs(f.x-e.x)<f.attackRange){f._hitThisAttack=true;resolveHit(f,e,f.attackKind==='heavy'?80:f.base.damage);}}}
function startAttack(f,kind){f.attackKind=kind;f.attackRange=f.id==='necromancer'&&kind==='heavy'?190:125;f.attackTime=f.id==='necromancer'?(kind==='heavy'?.85:.5):(kind==='heavy'?.52:.34);f.state='attack';f._hitThisAttack=false;if(f.id==='necromancer'&&kind==='heavy'){if(f.mana<5){f.attackTime=0;return;}f.mana-=5;}else if(kind==='heavy')f.stamina-=18;f.cooldown=f.id==='necromancer'?(kind==='heavy'?1:.5):f.cooldown;}
function resolveHit(a,d,damage){if(d.invuln>0)return;if(d.state==='guard'&&d.perfect>0){a.state='stun';a.stateTime=.45;d.perfect=0;announce('PERFECT',.7);burst(d.x,d.y,'#f2c85b',18);return;}if(d.state==='guard'){d.guard-=damage*.75;burst(d.x,d.y,d.base.color,6);if(d.guard<=0){d.guard=0;d.state='stun';d.stateTime=3;announce('GUARD BREAK',1);}return;}d.hp=clamp(d.hp-damage,0,d.base.hp);d.state='hit';d.stateTime=.2;d.flash=.15;d.vx=a.facing*120;a.combo++;a.comboDamage+=damage;a.comboTimer=1.15;a.ult=clamp(a.ult+damage*.8,0,100);d.ult=clamp(d.ult+damage*.35,0,100);if(a.id==='necromancer')a.mana=clamp(a.mana+1,0,100);burst(d.x,d.y,a.base.accent,10);if(d.hp<=0){if(a.id==='necromancer')a.corpses++;finishRound(a);}}
function useSkill(f,e){f.skillCooldown=3;if(f.id==='samurai'){f.perfect=.42;f.state='guard';f.stateTime=.5;announce('PARRY READY',.6);}else if(f.id==='necromancer'){if(f.mana<30||f.corpses<1){announce(f.corpses<1?'NO CORPSE':'NOT ENOUGH MANA',.6);return;}f.mana-=30;f.corpses--;f.summons++;game.objects.push({x:f.x+f.facing*90,y:530,w:38,h:65,type:'minion',life:15,owner:f});announce('UNDEAD RISES',.7);}else if(f.id==='soldier'){f.base.damage=f.base.damage===8?11:8;announce('WEAPON SWAP',.7);}else{e.state='stun';e.stateTime=.7;e.flash=.3;announce('FLASHED',.7);burst(e.x,e.y,'#f2c85b',15);}}
function useBinding(f,e){if(f.mana<20){announce('NOT ENOUGH MANA',.6);return;}f.mana-=20;f.skillCooldown=6;e.bindTime=3;e.slowUntil=3;e.hp=clamp(e.hp-50,0,e.base.hp);e.state='hit';e.stateTime=.25;announce('DEAD BIND',.7);burst(e.x,e.y,'#b08cff',20);if(e.hp<=0){if(f.id==='necromancer')f.corpses++;finishRound(f);}}
function useUltimate(f,e){f.ult=0;announce(f.base.ult,1);burst(f.x+f.facing*100,f.y,'#f2c85b',30);if(f.id==='samurai'){e.hp=clamp(e.hp-32,0,e.base.hp);e.state='hit';e.stateTime=.7;}else if(f.id==='necromancer'){f.areaTime=15;f.areaTick=0;e.slowUntil=15;game.objects.push({x:f.x,y:535,w:420,h:170,type:'grave',life:15});}else if(f.id==='soldier'){for(let i=0;i<4;i++)setTimeout(()=>{if(game&&game.running)resolveHit(f,e,10);},i*150);}else{game.objects.push({x:f.x+f.facing*100,y:500,w:30,h:80,type:'ally',life:8},{x:f.x+f.facing*145,y:500,w:30,h:80,type:'ally',life:8});}}
function finishRound(winner){if(game.roundOver)return;game.roundOver=true;winner.wins++;if(winner.id==='necromancer')winner.mana=clamp(winner.mana+10,0,100);announce(`${winner.base.name} WINS`,2);setTimeout(()=>{if(!game)return;if(winner.wins>=2){game.running=false;announce('MATCH COMPLETE',99);document.getElementById('matchStatus').textContent='MATCH COMPLETE';}else{game.round++;game.roundOver=false;game.timer=60;game.fighters.forEach(f=>{f.hp=f.base.hp;f.guard=f.base.guard;f.stamina=100;f.mana=f.id==='necromancer'?0:f.base.mana;f.ult=0;f.x=f.side===1?270:930;f.state='idle';f.corpses=0;f.summons=0;});announce(`ROUND ${game.round}`,1.5);}},2000);}
function update(dt){if(!game||!game.running)return;if(game.announceTime>0)game.announceTime-=dt;if(!game.roundOver){game.timer-=dt;if(game.timer<=0){const w=game.fighters[0].hp>=game.fighters[1].hp?game.fighters[0]:game.fighters[1];finishRound(w);}updateFighter(game.fighters[0],game.fighters[1],dt);updateFighter(game.fighters[1],game.fighters[0],dt);game.objects.forEach(o=>{if(o.type==='minion'&&o.owner&&o.life>0){const enemy=game.fighters.find(f=>f!==o.owner);o.cooldown=(o.cooldown||0)-dt;o.x+=Math.sign(enemy.x-o.x)*45*dt;if(o.cooldown<=0&&Math.abs(enemy.x-o.x)<115){o.cooldown=1.1;resolveHit(o.owner,enemy,o.owner.areaTime>0?18:12);}}});}game.particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=500*dt;p.life-=dt;});game.particles=game.particles.filter(p=>p.life>0);game.objects.forEach(o=>{if(o.life)o.life-=dt;});game.objects=game.objects.filter(o=>!o.life||o.life>0);updateHud();}
function draw(){ctx.clearRect(0,0,1200,650);drawArena();game.objects.forEach(drawObject);game.fighters.forEach(drawFighter);game.particles.forEach(p=>{ctx.globalAlpha=clamp(p.life*2,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size);});ctx.globalAlpha=1;document.getElementById('announce').textContent=game.announceTime>0?game.announce:'';}
function drawArena(){const g=ctx.createLinearGradient(0,0,0,650);g.addColorStop(0,'#202522');g.addColorStop(1,'#101312');ctx.fillStyle=g;ctx.fillRect(0,0,1200,650);ctx.fillStyle='#292e2b';ctx.fillRect(0,530,1200,120);ctx.strokeStyle='#4c514c';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,530);ctx.lineTo(1200,530);ctx.stroke();ctx.strokeStyle='rgba(139,216,193,.12)';for(let x=0;x<1200;x+=80){ctx.beginPath();ctx.moveTo(x,530);ctx.lineTo(x+40,650);ctx.stroke();}ctx.fillStyle='#566058';ctx.fillRect(90,120,100,7);ctx.fillRect(1010,180,110,7);ctx.fillStyle='#343a35';ctx.fillRect(140,128,9,155);ctx.fillRect(1050,188,9,180);}
function drawObject(o){ctx.save();if(o.type==='grave'){ctx.fillStyle='rgba(92,63,125,.4)';ctx.fillRect(o.x-o.w/2,o.y-o.h,o.w,o.h);ctx.strokeStyle='#b08cff';ctx.strokeRect(o.x-o.w/2,o.y-o.h,o.w,o.h);}else if(o.type==='crate'){ctx.fillStyle='#7e6042';ctx.fillRect(o.x-o.w/2,o.y-o.h,o.w,o.h);ctx.strokeStyle='#c59d69';ctx.strokeRect(o.x-o.w/2,o.y-o.h,o.w,o.h);ctx.beginPath();ctx.moveTo(o.x-o.w/2,o.y-o.h);ctx.lineTo(o.x+o.w/2,o.y);ctx.moveTo(o.x+o.w/2,o.y-o.h);ctx.lineTo(o.x-o.w/2,o.y);ctx.stroke();}else{ctx.fillStyle=o.type==='ally'?'#697379':'#a36c51';ctx.fillRect(o.x-15,o.y-o.h,30,o.h);ctx.fillRect(o.x-27,o.y-o.h,54,9);}ctx.restore();}
function drawFighter(f){ctx.save();ctx.translate(f.x,f.y);if(f.facing<0)ctx.scale(-1,1);ctx.globalAlpha=f.invuln>0?.55:1;ctx.fillStyle='rgba(0,0,0,.4)';ctx.beginPath();ctx.ellipse(0,5,42,9,0,0,TAU);ctx.fill();const body=f.state==='guard'?'#68716c':f.base.color;ctx.fillStyle=body;ctx.fillRect(-21,-92,42,80);ctx.fillStyle=f.base.accent;ctx.beginPath();ctx.arc(0,-111,21,0,TAU);ctx.fill();ctx.fillStyle='#171b19';ctx.fillRect(-16,-115,32,7);ctx.fillStyle=body;ctx.fillRect(-29,-83,9,43);ctx.fillRect(20,-83,9,43);if(f.state==='attack'){ctx.strokeStyle=f.base.accent;ctx.lineWidth=f.attackKind==='heavy'?11:7;ctx.beginPath();ctx.arc(30,-72,55,-.8,.8);ctx.stroke();}if(f.state==='guard'){ctx.strokeStyle='#f2c85b';ctx.lineWidth=6;ctx.beginPath();ctx.arc(20,-70,55,-1.1,1.1);ctx.stroke();}if(f.flash>0){ctx.fillStyle='#fff4b0';ctx.beginPath();ctx.arc(0,-70,70,0,TAU);ctx.fill();}ctx.restore();}
function updateHud(){if(!game)return;const[a,b]=game.fighters;document.getElementById('p1Name').textContent=a.base.name;document.getElementById('p2Name').textContent=b.base.name;document.getElementById('p1Hp').style.width=`${a.hp/a.base.hp*100}%`;document.getElementById('p2Hp').style.width=`${b.hp/b.base.hp*100}%`;document.getElementById('p1Guard').style.width=`${a.guard/a.base.guard*100}%`;document.getElementById('p2Guard').style.width=`${b.guard/b.base.guard*100}%`;document.getElementById('p1Stamina').style.width=`${a.stamina}%`;document.getElementById('p2Stamina').style.width=`${b.stamina}%`;document.getElementById('p1Mana').style.width=`${a.base.mana?a.mana:a.stamina}%`;document.getElementById('p2Mana').style.width=`${b.base.mana?b.mana:b.stamina}%`;document.getElementById('p1Ult').style.width=`${a.ult}%`;document.getElementById('p2Ult').style.width=`${b.ult}%`;document.getElementById('p1UltLabel').textContent=`ULTIMATE ${Math.round(a.ult)}%`;document.getElementById('p2UltLabel').textContent=`ULTIMATE ${Math.round(b.ult)}%`;document.getElementById('p1Wins').textContent='● '.repeat(a.wins)+'○ '.repeat(2-a.wins);document.getElementById('p2Wins').textContent='○ '.repeat(2-b.wins)+'● '.repeat(b.wins);document.getElementById('roundLabel').textContent=`ROUND ${game.round}`;document.getElementById('timer').textContent=Math.max(0,Math.ceil(game.timer));document.getElementById('p1Combo').textContent=a.combo;document.getElementById('p2Combo').textContent=b.combo;document.getElementById('p1Damage').textContent=`${a.comboDamage} DAMAGE`;document.getElementById('p2Damage').textContent=`${b.comboDamage} DAMAGE`;document.querySelector('.combo-p1').style.opacity=a.combo?1:0;document.querySelector('.combo-p2').style.opacity=b.combo?1:0;}
let last=0;function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;update(dt);draw();if(game&&(game.running||game.announceTime>0))requestAnimationFrame(loop);}